server:
  port: 9091

spring:

  datasource:
    url: ${URL_DB_CATALOG:jdbc:postgresql://localhost:5435/db-name-general}
    username: general
    password: general
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    liquibase: DEBUG
