version: '3.8'
services:
  catalog:
    build:
      context: ./catalog
      dockerfile: src/main/docker/Dockerfile
    container_name: my-catalog-container
    ports:
      - "7091:9091"
    depends_on:
      - db-client
    environment:
      - CATALOG_HOST=catalog
      - URL_DB_CATALOG=jdbc:postgresql://db-catalog:5432/db-catalog

  client:
    build:
      context: ./client
      dockerfile: src/main/docker/Dockerfile
    container_name: my-client-container
    ports:
      - "7092:9092"
    depends_on:
      - catalog
      - db-catalog
    environment:
      - CATALOG_HOST=catalog
      - URL_DB_CLIENT=jdbc:postgresql://db-client:5432/db-client

  db-catalog:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db-catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    ports:
      - 5433:5432
    volumes:
      - ./opt/catalog/pg-data:/var/lib/postgresql/data

  db-client:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db-client
      POSTGRES_USER: client
      POSTGRES_PASSWORD: client
    ports:
      - 5434:5432
    volumes:
      - ./opt/client/pg-data:/var/lib/postgresql/data