version: '3.8'
services:
  catalog:
    build:
      context: ./catalog
      dockerfile: src/main/docker/Dockerfile
    container_name: my-catalog-container
    ports:
      - "7091:9091"
    depends_on:
      - db-general
    environment:
      - CATALOG_HOST=catalog
      - URL_DB_CATALOG=jdbc:postgresql://db-general:5432/db-name-general

  client:
    build:
      context: ./client
      dockerfile: src/main/docker/Dockerfile
    container_name: my-client-container
    ports:
      - "7092:9092"
    depends_on:
      - catalog
      - db-general
    environment:
      - CATALOG_HOST=catalog
      - URL_DB_CLIENT=jdbc:postgresql://db-general:5432/db-name-general

  db-general:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db-name-general
      POSTGRES_USER: general
      POSTGRES_PASSWORD: general
    ports:
      - 5435:5432
    volumes:
      - ./opt/general/pg-data:/var/lib/postgresql/data
