server:
  port: 9092

spring:
  datasource:
    url: ${URL_DB_CLIENT:jdbc:postgresql://localhost:5435/db-name-general}
    username: general
    password: general
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

microservices:
  catalogHost: ${CATALOG_HOST:localhost}
  catalogPort: 9091
