server:
  port: 9092

spring:
#  datasource:
#    username: sa
#    password: pwd
#    url: jdbc:h2:file:./db/clientdb;MODE=PostgreSQL
#    driverClassName: org.h2.Driver
  datasource:
    url: ${URL_DB_CLIENT:jdbc:postgresql://localhost:5434/db-client}
    username: client
    password: client
    driver-class-name: org.postgresql.Driver

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

microservices:
#  catalogHost: localhost
  catalogHost: ${CATALOG_HOST:localhost}
  catalogPort: 9091
