server:
  port: 9092

spring:
  datasource:
    username: sa
    password: pwd
    url: jdbc:h2:file:./db/clientdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

my:
  hello: Hello my friend

microservices:
  catalogHost: localhost
  catalogPort: 9091
