@startuml

package "com.valentyn" {
    class BookDTO {
        -id: Long
        -title: String
        -author: String
    }

    class ClientDTO {
        -id: Long
        -name: String
        -email: String
    }

    BookDTO <-- ClientDTO : uses
}

@enduml